# Setup
title:        Web2Day
tagline:      
baseurl:      "https://github.com/SofteamOuest/web2day2018/"
paginate:     5
locale:       "fr"

# About/contact
author:
  name:       Mehdi EL KOUHEN
  url:        https://softeamouest.github.io

# Gems
plugins:
  - jekyll-paginate
  - jekyll-mermaid

#Others
markdown: kramdown

mermaid:
  src: 'https://cdn.jsdelivr.net/npm/mermaid@8.0.0-rc.8/dist/mermaid.js'
